Django_Tutorials/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("cbv.urls", namespace='cbv')),
    path('', include("books.urls", namespace='books')),
]

books/urls.py
from django.urls import path
from .views import IndexView, BookDetailView

app_name = 'books'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<slug:slug>/', BookDetailView.as_view(), name='book-detail'),
]

cbv/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from cbv.views import Ex2View, PostPreLoadTaskView, SinglePostView


app_name = 'cbv'

urlpatterns = [
    path('ex1', TemplateView.as_view(template_name="ex1.html", 
                                    extra_context={'title':'Custom Title'})),
    path('ex2', Ex2View.as_view(), name='ex2'),
    path('rdt', RedirectView.as_view(url='https://google.com'),
            name='google'),
    path('ex3/<int:pk>/', PostPreLoadTaskView.as_view(), name='redirect-task'),
    path('ex4/<int:pk>/', SinglePostView.as_view(), 
                            name='singlepost'), #singlepostpage
]

books/models.py
from django.db import models

class Books(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    count = models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.title 

cbv/models.py
from django.db import models


class Post(models.Model):
    name = models.CharField(max_length=100)
    count = models.IntegerField(null=True)

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from books.models import Books
from django.db.models import F
from django.utils import timezone


class IndexView(TemplateView):

    template_name = "home.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Books.objects.all()
        return context

class BookDetailView(DetailView):
    
    model = Books
    template_name = 'book-detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = Books.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count') + 1)

        context['time'] = timezone.now()

        return context

cbv/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView, RedirectView
from cbv.models import Post
from django.shortcuts import get_object_or_404
from django.db.models import F


class Ex2View(TemplateView):

    template_name = "ex2.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.get(id=1)
        context['data'] = "Context Data for Ex2"
        return context


class PostPreLoadTaskView(RedirectView):

    pattern_name = 'cbv:singlepost'

    def get_redirect_url(self, *args, **kwargs):
        # post = get_object_or_404(Post, pk=kwargs['pk'])
        # post.count = F('count') + 1
        # post.save()

        post = Post.objects.filter(pk=kwargs['pk'])
        post.update(count=F('count') + 1)

        return super().get_redirect_url(*args, **kwargs)


class SinglePostView(TemplateView):

    template_name = "ex4.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        return context

books/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome to Books {% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

books/templates/book-detail.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:800px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{book.title}}</h1>
        <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">{{book.genre}}</small>
            <small class="text-muted">{{book.isbn}}</small>
            <small class="text-muted">{{time}}</small>
        </div>
    </div>

</div>
{% endblock %}

books/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful Fictional Books To read.</p>
    </div>
    <div class="py-5">
        <div class="row">
            {% for book in books %}
            <div class="col-md-4">
                <a class="text-dark" href="{% url 'books:book-detail' slug=book.slug %}">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                {{book.title|truncatechars:50}}</h2>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{book.genre}}</small>
                                <small class="text-muted">{{book.isbn}}</small>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

cbv/templates/ex1.html
//Homepage
<hr/>
{{title}}
{{number}}

cbv/templates/ex2.html
//Example 2 - TemplateView within view.py

<hr/>
<a href="{% url 'cbv:google' %}">Google</a>
<hr/>
{{data}}
<hr/>
{{posts.name}}
<hr/>
<a href="{% url 'cbv:redirect-task' pk=posts.id %}">{{posts.name}}</a>

cbv/templates/ex4.html
//EXAMPLE 4 - Show single page
<hr/>
{{posts.name}}